### ISSUE TITLE
edit behavior of keyboard "ctrl-o" for opening line in notebook's edit mode

### ISSUE THREAD

**Issue by pavopax** [jupyter/help#38] opened 2016-05-12 18:08 UTC
Hi all, I'd like to propose a suggestion to edit the behavior of the keyboard shortcut "ctrl + o" (mac system) when in edit mode in a Jupyter notebook cell.

Current behavior: ctrl+o "opens" (inserts) a line above your current line, but the pointer remains at your current line.
Suggested behavior: open the line as above, but also move the pointer to the newly-created line.

Rationale: Mac OS X, Emacs, and perhaps other environments implement the second behavior, which is therefore more familiar to many users. 

Thanks all. Let me know if I need to clarify.

(Edit: Jupyter 4.1.0 on Mac OS X El Capitan and Safari)

**Comment by Carreau** [comment] 2016-05-12 18:18
> Current behavior: ctrl+o "opens" (inserts) a line above your current line, but the pointer remains at your current line.

I'm unable to reproduce this shortcut on my system, do you have any custom extensions?

Also this seem to be a [codemirror](http://codemirror.net/) keybinding, we tend to not change the default, but if it's a codemirror binding, it might be worth asking there to change the default to match other editors.

**Comment by pavopax** [comment] 2016-05-12 19:22
While I saw most of the keybindings I use, I didn't see 'ctrl-o' as a default on code mirror: https://codemirror.net/doc/manual.html#commands

It may also be mac and/or safari-specific. 

the point is, the behavior inside the notebook is inconsistent with behavior in all other environments on mac and also inside safari. Even inside this text box in code mirror, the behavior is like I suggest:
https://codemirror.net/1/jstest.html

**Comment by Carreau** [comment] 2016-05-12 19:32
> It may also be mac and/or safari-specific.

Ah, yes, it is safari specific, and not only in codemirror not the notebook.

https://support.apple.com/en-gu/HT201236

 > Control-O	|	Insert a new line after the insertion point. 

If it's Safari specific there is unfortunately, likely not much we can do.

**Comment by pavopax** [comment] 2016-05-12 20:23
To clarify, the keyboard shortcut is safari-specific, but the exact behavior of the shortcut is what's at issue. 

In all safari applications, the behavior is as I suggest, _except_ in the Jupyter notebook, where it behaves differently.

My suggestion is to make the shortcut _behavior_ to be the same in the notebook as in all other safari (and other) applications, where this shortcut is available.

**Comment by Carreau** [comment] 2016-05-12 21:28
Well the problem is that Safari has a specific behavior, and it's not the only one. It does "smart-paste" and sometime change `"` to curly-quote, insert space, newline, is picky with websocket. 
At some point you can't work-around all the safari specific "features".

Plus this is the CodeMirror default behavior, so the CodeMirror maintainer might decide it is worth it, 
we'll likely not maintain a patch on top of CodeMirror just for that. 

Though, I do agree that it would be nice to have a consistent behavior.

**Comment by pavopax** [comment] 2016-05-13 15:47
how do you know it's CodeMirror default? even on CodeMirror, it doesn't behave like in the notebook:

https://codemirror.net/1/jstest.html

**Comment by Carreau** [comment] 2016-05-13 16:57
That's codemirror 1 you link to. current version is 3 or 4, I do get the
same behavior in notebook and codemirror  demo on their main page. I'll re
check though.

**Comment by Carreau** [comment] 2016-05-13 18:14
Yep, I get the exact same behavior on both for safari:

Ctrl-o, Backspace repeated
![ctrlo](https://cloud.githubusercontent.com/assets/335567/15257503/71d1aee4-18fb-11e6-8a70-54bc92a19bec.gif)


So it is a things that is CodeMirror behavior, not Jupyter Notebook's.

Note the the behavior on codemirror 1 (which is a few years old is weird (only Ctrl-O, new line is deleted automatically)
![cm1](https://cloud.githubusercontent.com/assets/335567/15257565/c7904700-18fb-11e6-9a0d-33d9eb4f925e.gif)

**Comment by pavopax** [comment] 2016-05-14 20:33
Thanks so much for looking into this. Yes, that is a CodeMirror feature, and can be tested on their front page text box (which I didn't notice at first):
https://codemirror.net

I will alert the CodeMirror team to this behavior to try to modify.

**Comment by Carreau** [comment] 2016-05-14 20:44
Great, thanks !

**Comment by Carreau** [comment] 2016-10-26 17:34
Forgot to close, closing. Thanks!

**Closed by Carreau** 2016-10-26 17:34 UTC
