### ISSUE TITLE
GitHub LaTeX "Math Processing Error" when rendering Jupyter notebooks

### ISSUE THREAD

**Issue by rsvp** [jupyter/help#21] opened 2016-04-09 18:09 UTC
### Description of specific issue

Mathematical equations, in both inline and display modes,
render correctly when viewed in local browser --
however, when a Jupyter notebook with such equations
is viewed at GitHub the following message is generated:
**"Math Processing Error"**

The issue can be traced solely to GitHub since
a notebook's source commited to a GH repo viewed through
http://nbviewer.jupyter.org renders the math correctly.

### Expected behavior

Here's the correct renderings via
http://nbviewer.jupyter.org/github/rsvp/fecon235/blob/master/nb/qdl-spx-earn-div.ipynb
while noticing the actual source code resides at GitHub.

### Observed behavior

Here's the problematic rendering at GitHub:
https://github.com/rsvp/fecon235/blob/master/nb/qdl-spx-earn-div.ipynb
where all the LaTeX math is replaced by this message,
"Math Processing Error".

### Steps towards resolution?

It is not clear how (or if) LaTeX is being rendered at GitHub.

[ Added further details: https://github.com/rsvp/fecon235/issues/3 ]

**Comment by willingc** [comment] 2016-04-12 01:09
Hi @rsvp,

Thanks for writing this observation about GitHub rendering of notebooks.

Since this looks to be an upstream issue with GitHub since I don't believe that they currently support LaTeX rendering in their service, I'm labeling it as such. 

I've also added it to the Reference milestone in hopes that your research will help other users.

Thanks :cake:

**Comment by Carreau** [comment] 2016-04-13 07:34
> I don't believe that they currently support LaTeX rendering in their service, I'm labeling it as such.

They do support mathjax rendering, and actually it works here : 

<img width="628" alt="screen shot 2016-04-13 at 09 33 56" src="https://cloud.githubusercontent.com/assets/335567/14485994/ecf145d4-015a-11e6-8b76-6acdfd8c06d1.png">

It was likely a transient issue though.

**Comment by Carreau** [comment] 2016-04-13 07:35
(Note, they don't support **javascript** rendering, but otherwise they are also using nbconvert)

**Comment by rsvp** [comment] 2016-04-13 17:19
hi @Carreau, wondering how one can trace (and help fix) the code GitHub is using to render LaTeX? At this moment, that sample notebook is still giving "Math Processing Error" where LaTeX is embedded. Supposing that the problem is upstream, where should one create an issue? A few months ago we contacted GitHub directly, but got some vague misdirection, and could not even determine who were the primary developers. Thanks very much for checking in.

**Comment by Carreau** [comment] 2016-04-14 11:22
> hi @Carreau, wondering how one can trace (and help fix) the code GitHub is using to render LaTeX?

It's not possible, unless you are a GitHub employee, but I doubt the problem is upstream. But the GitHub is mostly "just" shelling out to nbconvert + some customisation.

It appears to works fine here with the notebook you link, so are you sure you do not have an extension in your browser that messes with results ? If I were able to reproduce i could investigate by looking at the page source. The math is rendered locally by your browser, so if the HTML is modified before the math is rendered you get these messages.

**Comment by rsvp** [comment] 2016-04-14 23:56
hi @Carreau, your suspicions are correct. I tested the GitHub rendering of 
https://github.com/rsvp/fecon235/blob/master/nb/qdl-spx-earn-div.ipynb
directly across four browsers:

* Firefox under Linux: LaTeX gives "Math Processing Error".
* Firefox under Android: LaTeX produces blanks, no error messages.
* Chromium under Linux: LaTeX produces choppy equations with incorrect line returns.
* Chrome under Android: LaTeX produces choppy equations with incorrect line returns.

These should be compared to the same notebook source code at GitHub,
but *correctly* rendered via the nbviewer at Jupyter:
http://nbviewer.jupyter.org/github/rsvp/fecon235/blob/master/nb/qdl-spx-earn-div.ipynb
and of course, if the notebook is loaded locally and viewed.

Perhaps we can conclude that somehow GitHub's nbconvert "customization"
invalidates Jupyter's correctness and also introduces incompatibilities 
across different browsers. But how? why? (security, really?) 
and what will it take for GitHub to fix this issue?

**Comment by rsvp** [comment] 2016-04-21 19:24
I would kindly like to request comments or suggested fixes from:
@tclem, @arfon, @sshirokov, @skalnik, @rgbkrk, and @bollwyvl
based on this announcement:
http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/

Also, @willingc, could you kindly "un"-close (re-open) this issue since your
given reason: "I don't believe that they currently support LaTeX rendering in their service"
turns out to be an incorrect personal belief. We are hoping that the LaTeX issue 
at GitHub can be fixed...

... for the communication of computational narratives and 
the sharing/replication of scientific and MATHEMATICAL results.

Thank you very much!

**Comment by jasongrout** [comment] 2016-04-21 22:50
> Perhaps we can conclude that somehow GitHub's nbconvert "customization"
> invalidates Jupyter's correctness and also introduces incompatibilities 
> across different browsers. But how? why? (security, really?) 
> and what will it take for GitHub to fix this important issue?

I think you're probably right here that this is a problem on Github's end, or at least it needs to be worked on by Github, since we don't see what they are doing to render the page. I also see problems with the Github rendering on Chrome on OS X.

**Comment by rgbkrk** [comment] 2016-04-22 00:35
If you care about 100% reliable renders, use nbviewer for rendering. Otherwise, open a support ticket with GitHub.

**Comment by willingc** [comment] 2016-04-22 01:24
Reopened as requested.

**Comment by jasongrout** [comment] 2016-04-22 14:39
> If you care about 100% reliable renders, use nbviewer for rendering. Otherwise, open a support ticket with GitHub.

+1

**Comment by jasongrout** [comment] 2016-05-05 19:23
Closing since this is clearly an issue we can not solve, but needs to be taken up by Github.

**Closed by jasongrout** 2016-05-05 19:23 UTC
Labels: upstream

**Comment by jasongrout** [comment] 2016-05-05 19:24
@rsvp - please pursue this with Github, and feel free to link this issue. Thanks for looking into this!
