### ISSUE TITLE
Kernel does not respond in jupyter notebook

### ISSUE THREAD

**Issue by Solrac3589** [jupyter/help#272] opened 2018-01-02 16:30 UTC
Hello everybody. I need help on trying to use jupyter notebook. I searched my error trough internet and i found it in another place.

https://stackoverflow.com/questions/35673530/i-am-using-jupyter-notebook-ipython-3-on-windows-whenever-i-am-starting-my-pyt

But i do not understand why i have this error, due to the fact that i have everything up to date , and was a temporary mistake error.

Just to be clear. I'm running ubuntu 16.04 and python 3.5. my jupyter version installed is 4.4

In order to install everything, i used the explanation in handson-ml book chapter 1.

When i open a file it tries to open the kernel until is says:

The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

In my terminal appears a lot of stuff, but i think the most relevant:

...
...
[W 17:23:19.090 NotebookApp] KernelRestarter: restart failed
[W 17:23:19.090 NotebookApp] Kernel 08960427-ddbb-4fd0-b4d6-aa8ee9d7a519 died, removing from map.
ERROR:root:kernel 08960427-ddbb-4fd0-b4d6-aa8ee9d7a519 restarted failed!
[W 17:23:19.134 NotebookApp] 410 DELETE /api/sessions/490c3f16-14b5-48c2-a691-25942df19430 (127.0.0.1): Kernel deleted before session
[W 17:23:19.135 NotebookApp] Kernel deleted before session
[W 17:23:19.135 NotebookApp] 410 DELETE /api/sessions/490c3f16-14b5-48c2-a691-25942df19430 (127.0.0.1) 1.98ms referer=http://localhost:8888/notebooks/handson-ml/01_the_machine_learning_landscape.ipynb
...
...

[W 17:23:19.090 NotebookApp] KernelRestarter: restart failed
[W 17:23:19.090 NotebookApp] Kernel 08960427-ddbb-4fd0-b4d6-aa8ee9d7a519 died, removing from map.
ERROR:root:kernel 08960427-ddbb-4fd0-b4d6-aa8ee9d7a519 restarted failed!
[W 17:23:19.134 NotebookApp] 410 DELETE /api/sessions/490c3f16-14b5-48c2-a691-25942df19430 (127.0.0.1): Kernel deleted before session
[W 17:23:19.135 NotebookApp] Kernel deleted before session
[W 17:23:19.135 NotebookApp] 410 DELETE /api/sessions/490c3f16-14b5-48c2-a691-25942df19430 (127.0.0.1) 1.98ms referer=http://localhost:8888/notebooks/handson-ml/01_the_machine_learning_landscape.ipynb

Thank you for any help.

**Comment by Solrac3589** [comment] 2018-01-02 16:54
Just to give a few mor info. before the restar of each attempt of the server, it gives this error (in the terminal):

TypeError: initialize() got an unexpected keyword argument 'make_current'

**Comment by Solrac3589** [comment] 2018-01-03 09:24
After many time trying everything and reinstalling every element in many versions, the only way i found to make it work was trough Anaconda.

IF somebody is asking which version i used, is Anaconda3-4.2.0-Linux-x86_64.sh (if I am not wrong is the 64 bits, python 3.5 version) from: 
https://repo.continuum.io/archive/index.html 

Anyway, i prefer to not close the issue yet, due to the fact that i did not had time to play with that and see if everything works fine (the only thing i saw is that the kernel runs). 
Soon I am going to give feedback about it and if it is okay, we will close that.

Thank you everybody anyway xD

**Comment by takluyver** [comment] 2018-01-03 12:35
Can you show more of the error message? Specifically, the lines above `TypeError: ...` ? Is it possible you've got an early version of Tornado 5 installed? We've got some fixes to be released soon for compatibility with tornado 5.

**Comment by Solrac3589** [comment] 2018-01-03 13:04
The full error between NotebookApp and NotebookApp is the following one.

WARNING:root:kernel b53ccc2c-8bcb-4242-945c-4f693b24b547 restarted
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/innova2/ml/env/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/innova2/ml/env/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/innova2/ml/env/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/innova2/ml/env/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 448, in initialize
    self.init_sockets()
  File "/home/innova2/ml/env/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 251, in init_sockets
    self.init_iopub(context)
  File "/home/innova2/ml/env/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 259, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/home/innova2/ml/env/lib/python3.5/site-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/home/innova2/ml/env/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'


This is repeated for each attempt.

My version of tornado is 4.5.2. I think this version should work, due to the fact that i have another computer with jupyter running and works correctly (yes, i have checked the other packages and they are also the same).

**Comment by takluyver** [comment] 2018-01-03 13:12
What version of pyzmq do you have?

**Comment by Solrac3589** [comment] 2018-01-03 14:02
16.0.3

**Comment by takluyver** [comment] 2018-01-03 14:10
Odd, I don't see how that should be a problem. @minrk may have an idea.

**Comment by jasonyzhang** [comment] 2018-01-12 00:35
Hi, I am getting the same error:

KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-121>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 448, in initialize
    self.init_sockets()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 251, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 259, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'


I am running Python 2.7.6 on Ubuntu 14.04. Jupyter version 4.4.0.

The problem isn't necessarily urgent, but I am curious as to what might be the cause.

**Comment by takluyver** [comment] 2018-01-12 10:18
Check your tornado version. If you have tornado 5.0a1, you'll need to downgrade to tornado 4.x for now. We're working on new releases.

**Comment by DavidWatkins** [comment] 2018-01-16 00:32
I am having the same issue with Ubuntu 16.04, Python 2.7.12, and Jupyter-core version 4.4.0. My pyzmq version is the same as @Solrac3589. Unsure what the cause might be. I installed jupyter just now using "pip2 install jupyter --user".

**Comment by minrk** [comment] 2018-01-16 04:01
I belive this is caused by using the prerelease of tornado 5.0. It should be fixed in ipykernel 4.7. FCan you share `pip list`?

**Comment by DavidWatkins** [comment] 2018-01-16 18:55
It turns out the reason for the problem was because of a Tornado version mismatch. The version I had on my PYTHONPATH was from ROS which uses version 4.0.2. Once I removed ROS from my PYTHONPATH I had no issue.

**Comment by mahmoudakl** [comment] 2018-01-25 15:22
I had the same problem as @DavidWatkins with the Tornado version mismatch because of ROS.
However, I found another solution. I had ipykernel 4.8 installed, and when I rolled it back to version 4.6 everything worked fine, without having to remove ROS from my PYTHONPATH.

**Comment by msunardi** [comment] 2018-02-07 00:45
Just to confirm. I had the same issue, and @mahmoudakl 's solution of rolling back ipykernel from 4.8.0 to 4.6.0 worked for me. I ran into the issue when running Spyder3 for python 3.6.3. Tornado at version 4.5.3.

**Comment by rickarmstrong** [comment] 2018-02-19 23:56
> Just to confirm. I had the same issue, and @mahmoudakl 's solution of rolling back ipykernel from 4.8.0 to 4.6.0 worked for me. I ran into the issue when running Spyder3 for python 3.6.3. Tornado at version 4.5.3.

Same here, but installing Jupyter into a 2.7 virtualenv. Hi msunardi. ;)

**Comment by jamessergeant** [comment] 2018-03-04 23:47
Rolling back to 4.6.0 also worked for me, thanks all

**Comment by jackiekazil** [comment] 2018-03-16 03:20
+1 had the same issue... I was on version 4.0.2 ... I did an update and it installed 5.0 and 5.0 worked. 
This ticket can probably be closed.

**Comment by takluyver** [comment] 2018-03-16 13:03
Thanks!

**Closed by takluyver** 2018-03-16 13:03 UTC

**Comment by oolongtea** [comment] 2018-09-13 14:48
Thanks @jackiekazil. `pip install tornado==5.0` fixed it since I was also on version 4.0.2.
